<?php include('header.php'); ?>

<div class="body">
    <div class="containerSuperiorTexto">
        <h1>Ingrese los datos para iniciar sesión</h1>
        <?php if (!($error === '')): ?>
        <p><?php echo $error; ?></p>
    <?php endif; ?>
    </div>
    <div class="containerInferior">
        <div class="formulario">
            <form method="post" action="VerificacionLogueo">
                <input name="user" type="text" placeholder="Ingrese usuario" required>
                <input name="password" type="password" placeholder="Ingrese contraseña" required>
                <button class="botonAgregar" type="submit">Ingresar</button>
            </form>
        </div>
    </div>
</div>

<?php include('footer.php'); ?>