<?php include('header.php'); ?>

<div class="body">
    <div class="containerSuperiorTexto">
        <h1>Peliculas de <?php echo $genero->genero ?></h1>
        <p><?php echo $genero->descripcion ?></p>
    </div>
    <div class="containerInferior">
        <ul>
            <?php foreach ($peliculas as $pelicula) {
                echo "<a href='InfoPelicula/" . urlencode($pelicula->titulo) . "'><li class='boton'> $pelicula->titulo </li></a>";
            } ?>
        </ul>
    </div>
    <div class="containerEspecial">
    <?php if (isset($_SESSION['usuario'])) { ?>
        <?php echo "<a href='Peliculas/AgregarPelicula/" . urlencode($genero->genero) . "'><span class='botonAgregar'>Agregar Pelicula</span></a>" ?>
    <?php } ?>
    </div>
</div>

<?php include('footer.php'); ?>