<?php include('header.php'); ?>

<div class="body">
    <div class="containerSuperior">
        <h1>Películas</h1>
    </div>
    <div class="containerInferior">
        <ul>
            <?php foreach ($peliculas as $pelicula) {
                foreach ($generos as $genero) {
                    if ($pelicula->id_genero == $genero->id_genero) {
                        echo "<a href='InfoPelicula/" . urlencode($pelicula->titulo) . "'><li class='boton'>$pelicula->titulo || $genero->genero</li></a>";
                    }
                }
            } ?>
            <?php if (isset($_SESSION['usuario'])) { ?>
                <a href='AgregarPelicula'><span class='botonAgregar'>Agregar Pelicula</span></a>
            <?php } ?>
        </ul>
    </div>
</div>

<?php include('footer.php'); ?>
