<?php include('header.php'); ?>

<div class="body">
    <div class="containerSuperior">
        <h1>Géneros</h1>
    </div>
    <div class="containerInferior">
        <ul>
            <?php foreach ($generos as $genero) {
                if (isset($_SESSION['usuario'])) {
                    echo "<div class='containerBotones'><a href='Peliculas/" . urlencode($genero->genero) . "'><li class='boton'> $genero->genero </li></a>
                        <a href='EliminarGenero/" . urlencode($genero->genero) . "'><span class='botonEliminar'>Eliminar</span></a>
                        <a href='EditarGenero/" . urlencode($genero->genero) . "'><span class='botonEditar'>Editar</span></a></div>";
                } else {
                    echo "<a href='Peliculas/" . urlencode($genero->genero) . "'><li class='boton'> $genero->genero </li></a>";
                }
            } ?>
            <?php if (isset($_SESSION['usuario'])) { ?>
                <a href='Peliculas'><li class='boton'>Todas las películas</li></a>
                <a href='AgregarGenero'><li class='botonAgregar'>Agregar Genero</li></a>
            <?php } ?>
        </ul>
    </div>
</div>

<?php include('footer.php'); ?>