<?php include('header.php'); ?>

<div class="body">
    <?php if ($error): ?>
        <p class="error"><?php echo $error; ?></p>
    <?php endif; ?>
    <divc class="containerSuperior">
        <h1>Agregar género</h1>
</div>
<div class="containerInferior">
    <div class="formulario">
        <form method="post" action="AgregarGenero">
            <input name="genero" type="text" placeholder="Ingrese el nombre del genero" required>
            <input name="descripcion" type="text" placeholder="Ingrese la descripcion del genero" required>
            <button class="botonAgregar" type="submit">Agregar</button>
        </form>
    </div>
</div>
</div>

<?php include('footer.php'); ?>