<?php include('header.php'); ?>

<div class="body">

    <div class="containerSuperiorTexto">
        <h1>Agregar pelicula</h1>
        <?php if (!($error === '')): ?>
            <p class="error"><?php echo htmlspecialchars($error); ?></p>
        <?php endif; ?>
    </div>
    <div class="containerInferior">
        <div class="formulario">
            <form method='post' action='AgregarPelicula'>
                <select name="genero" id="genero" required>
                    <option value="">Seleccione un género</option>
                    <?php foreach ($generos as $genero): ?>
                        <option value="<?php echo htmlspecialchars($genero->id_genero); ?>">
                            <?php echo htmlspecialchars($genero->genero); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <input name="titulo" type="text" placeholder="Ingrese el titulo de la pelicula" required>
                <input name="director" type="text" placeholder="Ingrese el director de la pelicula" required>
                <input name="descripcion" type="text" placeholder="Ingrese la descripcion de la pelicula" required>
                <input name="calificacion" type="number" placeholder="Ingrese la calificacion de la pelicula" required>
                <input name="estreno" type="date" placeholder="Ingrese el estreno de la pelicula" required>
                <button class="botonAgregar" type="submit">Agregar</button>
            </form>
        </div>
    </div>
</div>

<?php include('footer.php'); ?>